version: '3.1'

services:
  app:
    restart: always
    build: .
    environment:
      DB_HOST: db
    depends_on:
      - db
  db:
    restart: always
    image: postgres:12-alpine
    environment:
      POSTGRES_DB: app
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
